// Generated by kleverkeys-generator

#ifndef KLEVERKEYS_H
#define KLEVERKEYS_H

#include <string>
#include "HideString.h"

class KleverKeys {

public:
    static std::string get(std::string id);
};


#endif
